export const authTypes = {
  DO_AUTH: "auth/DO_AUTH",
  DO_SIGNOUT: "auth/DO_SIGNOUT",
  REGISTER_COMPLETED: "auth/REGISTER_COMPLETED",
  REGISTER_ERROR: "auth/REGISTER_ERROR",
  SIGNIN_SUCCESS: "auth/SIGNIN_SUCCESS",
  SIGNIN_ERROR: "auth/SIGNIN_ERROR",
};
